version: "3.7"
services:
  interface:
    build: ./interface
    image: interface
    ports:
      - "5000:5000"
    depends_on:
      - controller
  controller:
    build: ./controller
    image: controller
    ports:
      - "5001:5001"
    depends_on:
      - model
  model:
    build: ./model
    image: model
    ports:
      - "5002:5002"