version: "3.7"
services:
  interface:
    build: ./interface
    image: interface
    ports:
      - "5000:5000"
    depends_on:
      - controller
  controller:
    build: ./controller
    image: controller
    ports:
      - "5001:5001"
    depends_on:
      - model
      - cache
      - db
  model:
    build: ./model
    image: model
    ports:
      - "5002:5002"
  cache:
    image: redis
    command: --port 5003
    ports:
      - "5003:5003"
    volumes:
        - ./cache_data:/data
  db:
    image: mongo
    command: mongod --port 5004
    ports:
        - "5004:5004"